id: P2A27A523
initial_creation_type: input
source_metadata:
  title: Tsok Series
  language: de
  description: 'Lotsawa House presents the following texts related to the practice
    of tsok (tshogs) or feast-gathering (Skt. gaṇacakra):'
  volume:
    53e936d83d80473d8b315eca512c53d7:
      title: Introduction to Gaṇacakra (Tsok)
      parent: Introduction
    bbf579b7379e4029824e4b913e0c0e49:
      title: A Concise Explanation of Gaṇacakra
      parent: Explanation
    b90f058d5f53429ab0d981d959da34a2:
      title: 'A Bouquet of Uḍumbara Flowers: An Explanation of the Tenth Day'
      parent: Explanation
    5cde86cb35534ea39d1ceab7573c3f73:
      title: 'Music to Adorn the Illusory Display: A Concise Explanation of the Nature
        of the Feast Offering'
      parent: Explanation
    398e5ce1d9644d93805059a4a6249072:
      title: The Gaṇacakra Ritual
      parent: Explanation
    47f30001138d4fde86e73f10c589f879:
      title: 'Sweet Droplets of the Honey of Accomplishment: A Concise Explanation
        of the Indispensable Points of the Feast-Gathering'
      parent: Explanation
    b4b2578485c746be82bd84d64dbf2ee8:
      title: 'Bestowing the Glory of Wisdom: A Gaṇacakra Feast for Nyingtik Saldrön'
      parent: Offering Liturgies
    deebee5048f74e19b3534d245fed71ed:
      title: 'A Glorious Garland of the Two Accomplishments: An Abridged Feast-Offering
        for the Female Practice of the Ḍākinī'
      parent: Offering Liturgies
    9c01df5778e44f01b44f86a7a76c6d5e:
      title: The Brief Tsok Feast Offering Prayer from 'The Profound Path of the Ḍākinīs'
        Heart Drop'
      parent: Prayers
    8715e69087ef4b19be51f2072a522f44:
      title: 'Essence of Accomplishment: A Concise Feast-Offering to Noble Tārā'
      parent: Prayers
    c4634373eb04443cb25d908b4ead58a4:
      title: Short Tsok Offering to the Powerful Lady Kurukullā
      parent: Prayers
    a3b6cc2085e4499c9c88a98879a7122d:
      title: Brief Prayer of the Feast Gathering
      parent: Prayers
    59e896b0a08b453a9d874f928d6316f2:
      title: Confession and Fulfilment Insert for Accumulating the Practice of Turning
        Back the Summons of the Ḍākinīs
      parent: Prayers
    af7051efbd944c3ab24fab4728838b51:
      title: Food Offering Prayer
      parent: Prayers
    cf49c5d1f345490caab3e7fd3591de71:
      title: Concise Tsok Feast
      parent: Prayers
    373986208bfb44d6aa689c074aeec2af:
      title: 'Excellent Vase of Splendour: The Tsok Feast Offering to Accompany the
        Vajra Seven-Line Prayer'
      parent: Prayers
    dc6b29707d62481f8d0c1cd905892bf7:
      title: A Concise Feast Prayer
      parent: Prayers
    0ee371d1239c41b88cd146739373b09e:
      title: Remainder Torma Offering for Seven-Line Prayer Guru Yoga
      parent: Remainder Offering
    e0400c356b354231a5f5179e167d7968:
      title: The Song of the Vajra
      parent: Songs
    9a72fca0ef994d84b62e61a39a2d0a98:
      title: 'Ḍākinī’s Delight: A Song of the Feast'
      parent: Songs
    2c475a1718cd4e4f92ba7aa467569e31:
      title: 'Harmonious Clouds of Sublime and Lasting Bliss: A Vajra Song for the
        Tsok Feast Offering to Venerable and Exalted Vajrayoginī'
      parent: Songs
    314e511bb66e46928cdade96e5c7c744:
      title: 'Song and Dance to Delight the Ḍākas and Ḍākinīs: An Aspiration for the
        Sixfold Satisfaction of the Maṇḍala of the Feast-Gathering'
      parent: Songs
    d97d7c437dbb4f8b9ef1ab8a494b28ac:
      title: Song of the Feast (Tsok Lu)
      parent: Songs
created_at: '2022-03-01T06:26:39.645228'
last_modified_at: '2022-03-01T06:26:39.645234'
